# Copyright 2022 Kubespider
# SPDX-License-Identifier: Apache-2.0

name: Kubespider latest image build

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
    types:
        - assigned

jobs:
  build:
    if: github.event.pull_request.assigned == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cesign/kubespider:latest
