# Copyright 2022 Kubespider
# SPDX-License-Identifier: Apache-2.0

name: Kubespider deploy test

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build images
      run: |
        set -x
        docker build -t cesign/kubespider:latest -f Dockerfile ./
    
    - name: Deploy
      run: |
        set -x

        #1. Test deploy Kubespider
        bash hack/install.sh
        sleep 10
        docker ps | grep -e kubespider -e aria2-pro
        if [[ $? != 0 ]]; then
          exit 1
        fi

        #2. Test deploy baidu net disk
        bash hack/install_baidunetdisk.sh
        sleep 10
        docker ps | grep -e baidunetdisk
        if [[ $? != 0 ]]; then
          exit 1
        fi

        #3. Test deploy plex
        export PLEX_CLAIM=fake_claim
        bash hack/install_plex.sh
        sleep 10
        docker ps | grep -e plex
        if [[ $? != 0 ]]; then
          exit 1
        fi

        #4. Test deploy thunder
        bash hack/install_thunder.sh
        sleep 10
        docker ps | grep -e xunlei
        if [[ $? != 0 ]]; then
          exit 1
        fi
    
    - name: Find error
      if: ${{ failure() }}
      run: |
        docker ps -a
        docker logs baidunetdisk
        docker logs kubespider
        docker logs aria2-pro
        docker logs plex
        docker logs xunlei
